# Generated by Django 3.2.16 on 2025-05-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20250507_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['order'], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AddField(
            model_name='book',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
