# Generated by Django 3.2.16 on 2025-05-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='order',
            field=models.IntegerField(default=100, verbose_name='Порядок'),
        ),
    ]
