# Generated by Django 3.2.16 on 2025-05-10 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0009_alter_book_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название полки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание полки')),
                ('background_image', models.URLField(blank=True, help_text='URL изображения для фона полки', max_length=500, null=True, verbose_name='Фоновое изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('books', models.ManyToManyField(blank=True, related_name='shelves', to='books.Book', verbose_name='Книги на полке')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Полка',
                'verbose_name_plural': 'Полки',
                'ordering': ['-created_at', 'title'],
            },
        ),
    ]
