# Generated by Django 3.2.16 on 2025-05-10 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_shelf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, help_text='URL изображения для фона полки', max_length=500, null=True, verbose_name='Фоновое изображение')),
            ],
        ),
        migrations.AlterField(
            model_name='shelf',
            name='background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.background', verbose_name='Фон'),
        ),
    ]
