# Generated by Django 3.2.16 on 2025-05-12 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_achievement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='user',
            new_name='users',
        ),
    ]
