# Generated by Django 3.2 on 2025-05-13 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_rename_user_achievement_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agreement',
        ),
    ]
